[package]
name = "melior-macro"
version = "0.20.8"
edition.workspace = true
description = "Internal macros for Melior"
documentation = "https://mlir-rs.github.io/melior/melior/"
# readme.workspace = true
# repository.workspace = true
# license.workspace = true
# keywords.workspace = true

[lib]
proc-macro = true

[dependencies]
comrak = { version = "0.55.0", default-features = false }
convert_case = "0.12.0"
proc-macro2 = "1"
quote = "1"
regex = "1.12.4"
syn = { version = "3.0.2", features = ["extra-traits", "full"] }
tblgen = { path = "../../tblgen-rs", default-features = false, features = ["llvm22-0"] }
unindent = "0.2.4"

[dev-dependencies]
melior = { path = "../melior", features = ["ods-dialects"] }
mlir-sys = { path = "../../mlir-sys" }
pretty_assertions = "1.4.1"
trybuild = { version = "1.0.108", features = ["diff"] }

[build-dependencies]
cargo_metadata = "0.23.1"
