[package]
name = "melior"
version = "0.27.8"
edition = "2024"
description = "The rustic MLIR bindings in Rust"
documentation = "https://mlir-rs.github.io/melior/melior/"
# readme.workspace = true
# repository.workspace = true
# license.workspace = true
# keywords.workspace = true
categories = ["api-bindings"]

[dependencies]
melior-macro = { path = "../macro", version = "0.20.8" }
mlir-sys = { path = "../../mlir-sys" }

[dev-dependencies]
indoc = "2.0.7"
insta = "1.47.2"
pretty_assertions = "1.4.1"

[features]
# Enable the BlockExt trait (requires ods feature)
helpers = ["ods-dialects"]
ods-dialects = []
